<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="schunk_egp50">

    <xacro:macro name="schunk_egp50">


        <xacro:property name="base_diamter" value="0.075" />
        <xacro:property name="base_length" value="0.015" />
        <xacro:property name="body_length" value="0.05" />
        <xacro:property name="body_width" value="0.03" />
        <xacro:property name="body_height" value="0.0866" />
        <xacro:property name="pincer_height" value="0.014" />
        <xacro:property name="pincer_length" value="0.050" />
        <xacro:property name="pincer_width" value="0.018" />


        <material name="blue">
            <color rgba="0 0 1 1" />
        </material>

        <material name="green">
            <color rgba="0 1 0 1" />
        </material>

        <material name="white">
            <color rgba="1 1 1 1" />
        </material>


        <!--Base plate-->
        <link name="egp50_base_link">
            <visual>
                <geometry>
                    <cylinder length="${base_length}" radius="${base_diamter/2}" />
                </geometry>
                <material name="blue" />
                <origin rpy="0 0 0" xyz="0 0 ${base_length/2}" />
            </visual>
            <collision>
                <geometry>
                    <cylinder length="${base_length}" radius="${base_diamter/2}" />
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 0" />
            </collision>
        </link>

        <!--Main gripper-->
        <link name="egp50_body_link">
            <visual>
                <geometry>
                    <mesh filename="package://workcell_description/meshes/Gripper.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <origin rpy="${pi/2} 0 0" xyz="${-body_length/2} ${body_width/2} ${-body_height/2}" />
                <material name="green" />
            </visual>
            <collision>
                <geometry>
                    <mesh filename="package://workcell_description/meshes/Gripper.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 0" />
            </collision>
            <inertial>
                <mass value="0.51" />
                <inertia ixx="0.0007" iyy="0.0001" izz="0.0006" ixy="0.0" ixz="0.0" iyz="0.0" />
            </inertial>
        </link>

        <!--Pincer block 1-->
        <link name="egp50_pincer_1_link">
            <visual>
                <geometry>
                    <mesh filename="package://workcell_description/meshes/Pincer_1.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <origin rpy="${pi/2} 0 0" xyz="${-body_length/2} ${pincer_width/2} ${-body_height-pincer_height/2}" />
                <material name="white" />
            </visual>
            <collision>
                <geometry>
                    <mesh filename="package://workcell_description/meshes/Pincer_1.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <origin rpy="${pi/2} 0 0" xyz="${-body_length/2} ${pincer_width/2} ${-body_height-pincer_height/2}" />
            </collision>
            <inertial>
                <mass value="0.51" />
                <inertia ixx="0.0007" iyy="0.0001" izz="0.0006" ixy="0.0" ixz="0.0" iyz="0.0" />
            </inertial>
        </link>


        <!--Pincer block 2-->
        <link name="egp50_pincer_2_link">
            <visual>
                <geometry>
                    <mesh filename="package://workcell_description/meshes/Pincer_2.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <origin rpy="${pi/2} 0 0" xyz="${-body_length/2} ${pincer_width/2} ${-body_height-pincer_height/2}" />
                <material name="blue" />
            </visual>
            <collision>
                <geometry>
                    <mesh filename="package://workcell_description/meshes/Pincer_2.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <origin rpy="${pi/2} 0 0" xyz="${-body_length/2} ${pincer_width/2} ${-body_height-pincer_height/2}" />
            </collision>
            <inertial>
                <mass value="0.51" />
                <inertia ixx="0.0007" iyy="0.0001" izz="0.0006" ixy="0.0" ixz="0.0" iyz="0.0" />
            </inertial>
        </link>


        <!-- Virtual link for visualizytion and planning-->
        <link name="egp_50_tip" />


        <!-- Joints-->

        <joint name="egp50_body_joint" type="fixed">
            <parent link="egp50_base_link" />
            <child link="egp50_body_link" />
            <origin xyz="0.0 0.0 ${base_length+body_height/2}" rpy="0.0 0.0 0.0" />
        </joint>

        <joint name="egp50_pincer_1_joint" type="prismatic">
            <parent link="egp50_body_link" />
            <child link="egp50_pincer_1_link" />
            <origin xyz="0.0 0.0 ${body_height/2+pincer_height/2}" rpy="0.0 0.0 0.0" />
            <!-- the motion of the pincer is along the X axis -->
            <axis xyz="1 0 0"/>
            <!-- the motion of the pincer is limited to the half of the gripper body length -->
            <limit lower="0" upper="${body_length/2}" velocity="100" effort="100"/>  
        </joint>

        <joint name="egp50_pincer_2_joint" type="prismatic">
            <parent link="egp50_body_link" />
            <child link="egp50_pincer_2_link" />
            <origin xyz="0.0 0.002 ${body_height/2+pincer_height/2}" rpy="0.0 0.0 0.0" />
            <!-- the motion of the pincer is along the X axis -->
            <axis xyz="1 0 0"/>
            <!-- the motion of the pincer is limited to the half of the gripper body length -->
            <limit lower="0" upper="${body_length/2}" velocity="100" effort="100"/> 
        </joint>

        <joint name="egp50_tip_joint" type="fixed">
            <parent link="egp50_pincer_1_link" />
            <child link="egp_50_tip" />
            <origin xyz="0.0 0.0 ${pincer_height/2}" rpy="0.0 0.0 0.0" />
        </joint>


    </xacro:macro>
</robot>